
all:
	echo "run command \"make que<number>\" to execute file for que<number>"
	echo "for instance, please run \"make que1\" to execute file que1.cpp"

que1: que1.cpp
	g++ -o que1 que1.cpp
	./que1


que2: que2.cpp
	g++ -o que2 que2.cpp
	./que2


que3: que3.cpp
	g++ -o que3 que3.cpp
	./que3


que4: que4.cpp
	g++ -o que4 que4.cpp
	./que4


que5: que5.cpp
	g++ -o que5 que5.cpp
	# ./que5


que6a: que6a.cpp
	g++ -o que6a que6a.cpp
	./que6a

que6b: que6b.cpp
	g++ -o que6b que6b.cpp
	./que6b